name: AUnit Tests

on: [push]

env:
  ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: "http://arduino.esp8266.com/stable/package_esp8266com_index.json https://espressif.github.io/arduino-esp32/package_esp32_dev_index.json"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1

    - name: Install platform
      run:  |
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266
        arduino-cli core install esp32:esp32

    
    - name: Install dependencies
      run:  |
        arduino-cli lib install AUnit
        git clone https://github.com/bxparks/EpoxyDuino
        
    - name: Verify tests
      run: |
        ls -all arduino/
        ls -all arduino/*
        make -C HeishaMon/tests clean
        make -C HeishaMon/tests tests
        make -C HeishaMon/tests runtests
